=== rodas404/TP-ID2023/escritores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="escritor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nomeCompleto"/>
				<xs:element ref="nacionalidade"/>
				<xs:element ref="fotografia" minOccurs="0"/>
				<xs:element ref="nascimento"/>
				<xs:element ref="morte" minOccurs="0"/>
				<xs:element ref="generos"/>
				<xs:element ref="ocupacoes"/>
				<xs:element ref="obrasEmDestaque"/>
				<xs:element ref="premios" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="nome" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="nascimento">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="data"/>
				<xs:element ref="ano"/>
				<xs:element ref="local"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ano" type="xs:string"/>
	<xs:element name="data" type="xs:string"/>
	<xs:element name="premio">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="ano" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="premios">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="premio" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="obrasEmDestaque">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="obra" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="escritores">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="escritor" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string"/>
	<xs:element name="local" type="xs:string"/>
	<xs:element name="ocupacoes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ocupacao" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="obra" type="xs:string"/>
	<xs:element name="ocupacao" type="xs:string"/>
	<xs:element name="morte">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="data"/>
				<xs:element ref="ano"/>
				<xs:element ref="local"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="genero" type="xs:string"/>
	<xs:element name="generos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="genero" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nacionalidade" type="xs:string"/>
	<xs:element name="nomeCompleto" type="xs:string"/>
</xs:schema>

=== rodas404/TP-ID2023/escritores.xml
<?xml version="1.0" encoding="utf-8"?>
<escritores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="escritores.xsd">
     <escritor nome="Daniel Silva" id="1">
          <nomeCompleto>Daniel Silva</nomeCompleto>
          <nacionalidade>Norte-americano</nacionalidade>
          <fotografia>https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/DanielSilva01.JPG/200px-DanielSilva01.JPG</fotografia>
          <nascimento>
               <data>1960</data>
               <ano>1960</ano>
               <local>Michigan</local>
          </nascimento>
          <generos />
          <ocupacoes>
               <ocupacao>escritor</ocupacao>
               <ocupacao>jornalista</ocupacao>
               <ocupacao>romancista</ocupacao>
               <ocupacao>crime fiction writer</ocupacao>
          </ocupacoes>
          <obrasEmDestaque>
               <obra>Morte em Viena</obra>
          </obrasEmDestaque>
     </escritor>
     <escritor nome="Oscar Wilde" id="2">
          <nomeCompleto>Oscar Fingal O'Flahertie Wills Wilde</nomeCompleto>
          <nacionalidade>Irlandês</nacionalidade>
          <fotografia>https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Oscar_Wilde_portrait_by_Napoleon_Sarony_-_albumen.jpg/250px-Oscar_Wilde_portrait_by_Napoleon_Sarony_-_albumen.jpg</fotografia>
          <nascimento>
               <data>16 de outubro 1854</data>
               <ano>1854</ano>
               <local>Dublin, Reino Unido da Grã-Bretanha e Irlanda</local>
          </nascimento>
          <morte>
               <data>30 de novembro 1900</data>
               <ano>1900</ano>
               <local>Paris, França</local>
          </morte>
          <generos>
               <genero>Drama</genero>
               <genero>conto</genero>
               <genero>diálogo</genero>
          </generos>
          <ocupacoes>
               <ocupacao>poeta</ocupacao>
               <ocupacao>dramaturgo</ocupacao>
               <ocupacao>contista</ocupacao>
               <ocupacao>jornalista</ocupacao>
               <ocupacao>escritor de literatura infantil</ocupacao>
               <ocupacao>romancista</ocupacao>
               <ocupacao>escritor</ocupacao>
               <ocupacao>autor</ocupacao>
               <ocupacao>prosista</ocupacao>
               <ocupacao>jornalista de opinião</ocupacao>
               <ocupacao>ensaísta</ocupacao>
               <ocupacao>fabulista</ocupacao>
          </ocupacoes>
          <obrasEmDestaque>
               <obra>The Importance of Being Earnest</obra>
               <obra>O Retrato de Dorian Gray</obra>
          </obrasEmDestaque>
          <premios>
               <premio ano="1878">Newdigate Prize</premio>
          </premios>
     </escritor>
     <escritor nome="Nicholas Sparks" id="3">
          <nomeCompleto>Nicholas Charles Sparks</nomeCompleto>
          <nacionalidade>Norte-americano</nacionalidade>
          <fotografia>https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Nicholas-Sparks-Autograph-1-4-06.jpg/250px-Nicholas-Sparks-Autograph-1-4-06.jpg</fotografia>
          <nascimento>
               <data>31 de dezembro 1965</data>
               <ano>1965</ano>
               <local>Omaha, Nebraska</local>
          </nascimento>
          <generos />
          <ocupacoes>
               <ocupacao>Escritor</ocupacao>
               <ocupacao>roteirista</ocupacao>
               <ocupacao>produtor</ocupacao>
          </ocupacoes>
          <obrasEmDestaque>
               <obra>The Notebook</obra>
          </obrasEmDestaque>
     </escritor>
     <escritor nome="Fernando Pessoa" id="4">
          <nomeCompleto>Fernando António Nogueira Pessoa</nomeCompleto>
          <nacionalidade>Português</nacionalidade>
          <fotografia>https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Pessoa_chapeu.jpg/200px-Pessoa_chapeu.jpg</fotografia>
          <nascimento>
               <data>13 de junho 1888</data>
               <ano>1888</ano>
               <local>Lisboa, Mártires, Reino de Portugal</local>
          </nascimento>
          <morte>
               <data>30 de novembro 1935</data>
               <ano>1935</ano>
               <local>Lisboa, Santa Catarina, Portugal</local>
          </morte>
          <generos />
          <ocupacoes>
               <ocupacao>Poeta</ocupacao>
               <ocupacao>escritor</ocupacao>
               <ocupacao>tradutor</ocupacao>
          </ocupacoes>
          <obrasEmDestaque>
               <obra>Mensagem</obra>
               <obra>Livro do Desassossego</obra>
          </obrasEmDestaque>
          <premios>
               <premio ano="1903">Queen Victoria Prize</premio>
               <premio ano="1934">Prémio Antero de Quental</premio>
          </premios>
     </escritor>
     <escritor nome="Paulo Coelho" id="5">
          <nomeCompleto>Paulo Coelho de Souza</nomeCompleto>
          <nacionalidade>Brasileiro</nacionalidade>
          <fotografia>https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Paulo_Coelho_30102007.jpg/220px-Paulo_Coelho_30102007.jpg</fotografia>
          <nascimento>
               <data>24 de agosto 1947</data>
               <ano>1947</ano>
               <local>Rio de Janeiro, DF</local>
          </nascimento>
          <generos>
               <genero>Drama</genero>
               <genero>romance</genero>
          </generos>
          <ocupacoes>
               <ocupacao>Escritor</ocupacao>
               <ocupacao>letrista</ocupacao>
               <ocupacao>jornalista</ocupacao>
               <ocupacao>compositor</ocupacao>
          </ocupacoes>
          <obrasEmDestaque>
               <obra>O Alquimista</obra>
          </obrasEmDestaque>
     </escritor>
     <escritor nome="José Luís Peixoto" id="6">
          <nomeCompleto>José Luís Marques Peixoto</nomeCompleto>
          <nacionalidade>Português</nacionalidade>
          <fotografia>https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/JoseLuisPeixoto.JPG/223px-JoseLuisPeixoto.JPG</fotografia>
          <nascimento>
               <data>4 de setembro 1974</data>
               <ano>1974</ano>
               <local>Galveias, Ponte de Sor</local>
          </nascimento>
          <generos />
          <ocupacoes>
               <ocupacao>Escritor</ocupacao>
               <ocupacao>dramaturgo</ocupacao>
               <ocupacao>poeta</ocupacao>
          </ocupacoes>
          <obrasEmDestaque>
               <obra>Morreste-me</obra>
               <obra>Nenhum Olhar</obra>
               <obra>Cemitério de Pianos</obra>
               <obra>Livro</obra>
               <obra>Dentro do Segredo</obra>
               <obra>Galveias</obra>
               <obra>Em Teu Ventre</obra>
               <obra>Autobiografia</obra>
               <obra>Almoço de Domingo</obra>
          </obrasEmDestaque>
          <premios>
               <premio ano="2001">Prémio José Saramago</premio>
               <premio ano="2008">Prémio de Poesia Daniel Faria</premio>
               <premio ano="2007">Prémio Cálamo Outra Mirada</premio>
               <premio ano="2013">Prémio Libro d' Europa</premio>
               <premio ano="2013">Prémio Sociedade Portuguesa de Autores</premio>
               <premio ano="2016">Oceanos-Prêmio de Literatura em Língua Portuguesa</premio>
               <premio ano="2019">The Best Translation Award-Japan</premio>
          </premios>
     </escritor>
     <escritor nome="Isabel Allende" id="7">
          <nomeCompleto>Isabel Allende Llona</nomeCompleto>
          <nacionalidade>Chilena</nacionalidade>
          <fotografia>https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Isabel_allende.jpg/200px-Isabel_allende.jpg</fotografia>
          <nascimento>
               <data>2 de agosto 1942</data>
               <ano>1942</ano>
               <local>Lima, Peru</local>
          </nascimento>
          <generos />
          <ocupacoes />
          <obrasEmDestaque>
               <obra>A Casa dos Espíritos</obra>
          </obrasEmDestaque>
          <premios>
               <premio ano="2010">Prêmio Nacional de Literatura do Chile</premio>
               <premio ano="2014">Medalha Presidencial da Liberdade</premio>
          </premios>
     </escritor>
     <escritor nome="Julian Barnes" id="8">
          <nomeCompleto>Julian Patrick Barnes</nomeCompleto>
          <nacionalidade>Britânica</nacionalidade>
          <fotografia>https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Julian_Barnes_in_2019_02.jpg/200px-Julian_Barnes_in_2019_02.jpg</fotografia>
          <nascimento>
               <data>19 de janeiro 1946</data>
               <ano>1946</ano>
               <local>Leicester, Reino Unido</local>
          </nascimento>
          <generos>
               <genero>Romance</genero>
               <genero>conto</genero>
          </generos>
          <ocupacoes />
          <obrasEmDestaque>
               <obra>O papagaio de Flaubert</obra>
          </obrasEmDestaque>
          <premios>
               <premio ano="1986">Prémio Médicis ensaio</premio>
               <premio ano="1992">Prémio Femina estrangeiro</premio>
               <premio ano="2011">Prémio Man Booker</premio>
          </premios>
     </escritor>
     <escritor nome="João Tordo" id="9">
          <nomeCompleto>João Tordo</nomeCompleto>
          <nacionalidade>Português</nacionalidade>
          <fotografia>https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Jo%C3%A3o_Tordo.jpg/200px-Jo%C3%A3o_Tordo.jpg</fotografia>
          <nascimento>
               <data>28 de agosto 1975</data>
               <ano>1975</ano>
               <local>Lisboa</local>
          </nascimento>
          <generos />
          <ocupacoes>
               <ocupacao>Jornalista</ocupacao>
               <ocupacao>escritor</ocupacao>
               <ocupacao>argumentista</ocupacao>
          </ocupacoes>
          <obrasEmDestaque />
          <premios>
