=== rodas404/TP-ID2023/obras.dtd
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT preco (#PCDATA)>
<!ELEMENT editora (#PCDATA)>
<!ELEMENT capa (#PCDATA)>
<!ELEMENT livro (titulo,preco,editora,capa)>
<!ELEMENT escritor (livro)+>
<!ELEMENT obras (escritor)+>

<!ATTLIST livro isbn CDATA #REQUIRED>

<!ATTLIST escritor nome CDATA #REQUIRED>
<!ATTLIST escritor id CDATA #REQUIRED>

<!ATTLIST obras xmlns:xsi CDATA #IMPLIED>
<!ATTLIST obras xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== rodas404/TP-ID2023/obras.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE obras SYSTEM "obras.dtd">
<obras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="obras.xsd">
     <escritor nome="Daniel Silva" id="1">
          <livro isbn="9788491398028">
               <titulo>Retrato de uma Desconhecida</titulo>
               <preco>18,81</preco>
               <editora>HARPER COLLINS</editora>
               <capa>https://img.bertrand.pt/images/retrato-de-uma-desconhecida-daniel-silva/NDV8MjgxMzE2Nzd8MjQ1MjY1Nzl8MTY3NTE2MjYzMDAwMA==/500x</capa>
          </livro>
          <livro isbn="9789722533911">
               <titulo>O Assalto</titulo>
               <preco>8,00</preco>
               <editora>11 X 17</editora>
               <capa>https://img.bertrand.pt/images/o-assalto-daniel-silva/NDV8MTkyODk2NTR8MTUwOTU5NzV8MTUwMzMyNDE1NjAwMA==/500x</capa>
          </livro>
          <livro isbn="9789722532136">
               <titulo>O Anjo Caído</titulo>
               <preco>8,00</preco>
               <editora>11 X 17</editora>
               <capa>https://img.bertrand.pt/images/o-anjo-caido-daniel-silva/NDV8MTc0MzY1MzF8MTMwNzAxNjJ8MTQ2MDM3MzM1OTAwMA==/500x</capa>
          </livro>
          <livro isbn="9789722533584">
               <titulo>A Rapariga Inglesa</titulo>
               <preco>8,00</preco>
               <editora>11 X 17</editora>
               <capa>https://img.bertrand.pt/images/a-rapariga-inglesa-daniel-silva/NDV8MTkwMDU5MTl8MTQ3Njk1MzJ8MTQ4ODU1NzQ5MjAwMA==/500x</capa>
          </livro>
          <livro isbn="9789722530408">
               <titulo>Retrato de Uma Espia</titulo>
               <preco>8,00</preco>
               <editora>11 X 17</editora>
               <capa>https://img.bertrand.pt/images/retrato-de-uma-espia-daniel-silva/NDV8MTYyNjk5ODZ8MTE4NTMyMzJ8MTQzNDEyODAxMzAwMA==/500x</capa>
          </livro>
     </escritor>
     <escritor nome="Nicholas Sparks" id="3">
          <livro isbn="9789892355214">
               <titulo>Um Sonho Só Nosso</titulo>
               <preco>17,01</preco>
               <editora>Edições Asa</editora>
               <capa>https://img.bertrand.pt/images/um-sonho-so-nosso-nicholas-sparks/NDV8MjczNDgzODN8MjM3MDA1NjV8MTY2MTQ0MjI0MDAwMA==/500x</capa>
          </livro>
          <livro isbn="9789892352008">
               <titulo>O Sonho</titulo>
               <preco>16,65</preco>
               <editora>Edições Asa</editora>
               <capa>https://img.bertrand.pt/images/o-sonho-nicholas-sparks/NDV8MjUzODE4OTB8MjE2MTExNDB8MTYzMDQyMjA1MTAwMA==/500x</capa>
          </livro>
          <livro isbn="9789892349206">
               <titulo>O Regresso</titulo>
               <preco>15,12</preco>
               <editora>Edições Asa</editora>
               <capa>https://img.bertrand.pt/images/o-regresso-nicholas-sparks/NDV8MjQzMDI4NDF8MjAzODcwOTR8MTU5ODQzNjM1MzAwMA==/500x</capa>
          </livro>
          <livro isbn="9789892323404">
               <titulo>Uma Promessa para Toda a Vida</titulo>
               <preco>14,32</preco>
               <editora>Edições Asa</editora>
               <capa>https://img.bertrand.pt/images/uma-promessa-para-toda-a-vida-nicholas-sparks/NDV8MTQ5MzA2NTl8MTA0MTQ2Mjd8MTM4MzU5MDI0NDAwMA==/500x</capa>
          </livro>
          <livro isbn="9780751567861">
               <titulo>Untitled Nicholas Sparks 3</titulo>
               <preco>19,56</preco>
               <editora>LITTLE, BROWN BOOK GROUP</editora>
               <capa>https://img.bertrand.pt/images/untitled-nicholas-sparks-3-nicholas-sparks/NDV8MjQ0ODc2MzF8MjA1ODAyMjB8MTY2OTIyNDUyNDAwMA==/500x</capa>
          </livro>
     </escritor>
     <escritor nome="Fernando Pessoa" id="4">
          <livro isbn="978-972-37-2318-2">
               <titulo>Poesia, Ricardo Reis</titulo>
               <preco>16,97</preco>
               <editora>Assírio &amp; Alvim</editora>
               <capa>https://img.bertrand.pt/images/poesia-ricardo-reis-fernando-pessoa/NDV8MTEyMzcwNTJ8MjQ3NjYxODJ8MTY4MzcyOTUzMDAwMA==/500x</capa>
          </livro>
          <livro isbn="978-972-0-79310-2">
               <titulo>Cartas de Amor de Fernando Pessoa e Ofélia Queiroz</titulo>
               <preco>15,08</preco>
               <editora>Assírio &amp; Alvim</editora>
               <capa>https://img.bertrand.pt/images/cartas-de-amor-de-fernando-pessoa-e-ofelia-queiroz-fernando-pessoa/NDV8MTMwMjk2MjN8MTg3MTg3MTZ8MTU1MTI1OTA4MDAwMA==/500x</capa>
          </livro>
          <livro isbn="9789896152413">
               <titulo>Palavras do Livro do Desassossego | Words from The Book of Disquiet</titulo>
               <preco>14,99</preco>
               <editora>Edições Centro Atlântico</editora>
               <capa>https://img.bertrand.pt/images/palavras-do-livro-do-desassossego-words-from-the-book-of-disquiet-fernando-pessoa/NDV8Mjg1OTcwNTl8MjQ5Nzc5NzR8MTY4NTM3ODQ5MzAwMA==/500x</capa>
          </livro>
          <livro isbn="9789722369657">
               <titulo>Poesia de Fernando Pessoa</titulo>
               <preco>14,31</preco>
               <editora>Editorial Presença</editora>
               <capa>https://img.bertrand.pt/images/poesia-de-fernando-pessoa-fernando-pessoa/NDV8MjcyNTI0Mjl8MjM1ODc5OTF8MTY1ODgyNjg5ODAwMA==/500x</capa>
          </livro>
     </escritor>
     <escritor nome="Paulo Coelho" id="5">
          <livro isbn="9789722524223">
               <titulo>O Alquimista</titulo>
               <preco>6,40</preco>
               <editora>11 X 17</editora>
               <capa>https://img.bertrand.pt/images/o-alquimista-paulo-coelho/NDV8MTUyMzcxMzl8MTA3MjU0NzV8MTY0NjM5OTYyNDAwMA==/500x</capa>
          </livro>
          <livro isbn="9789896877897">
               <titulo>O Alquimista</titulo>
               <preco>14,94</preco>
               <editora>Pergaminho</editora>
               <capa>https://img.bertrand.pt/images/o-alquimista-paulo-coelho/NDV8MjczOTU2OTh8MjM3NTQ4NTJ8MTY2NjYyNDA1MDAwMA==/500x</capa>
          </livro>
          <livro isbn="9789722525732">
               <titulo>O Diário de Um Mago</titulo>
               <preco>6,40</preco>
               <editora>11 X 17</editora>
               <capa>https://img.bertrand.pt/images/o-diario-de-um-mago-paulo-coelho/NDV8MTQ3MzQxMzh8MTAyMTYxMTB8MTM4MzU4OTc3MjAwMA==/500x</capa>
          </livro>
          <livro isbn="9789722531689">
               <titulo>O Aleph</titulo>
               <preco>6,40</preco>
               <editora>11 X 17</editora>
               <capa>https://img.bertrand.pt/images/o-aleph-paulo-coelho/NDV8MTcwMzg1ODV8MTI2NjIyMzJ8MTQ4NzMyNzM1NzAwMA==/500x</capa>
          </livro>
          <livro isbn="9789896877903">
               <titulo>Na Margem do Rio Piedra Eu Sentei e Chorei</titulo>
               <preco>14,94</preco>
               <editora>Pergaminho</editora>
               <capa>https://img.bertrand.pt/images/na-margem-do-rio-piedra-eu-sentei-e-chorei-paulo-coelho/NDV8MjczOTU3MTh8MjM3NTQ5MzR8MTY3MTA5Nzg5NjAwMA==/500x</capa>
          </livro>
     </escritor>
     <escritor nome="José Luís Peixoto" id="6">
          <livro isbn="9789897224607">
               <titulo>Almoço de Domingo</titulo>
               <preco>14,16</preco>
               <editora>Quetzal Editores</editora>
               <capa>https://img.bertrand.pt/images/almoco-de-domingo-jose-luis-peixoto/NDV8MjEzMzIxOTh8MTcyMTgzNDJ8MTYxNDg4MzAwNzAwMA==/500x</capa>
          </livro>
          <livro isbn="9789897226809">
               <titulo>Morreste-me</titulo>
               <preco>12,95</preco>
               <editora>Quetzal Editores</editora>
               <capa>https://img.bertrand.pt/images/morreste-me-jose-luis-peixoto/NDV8MjUxNzY0Nzd8MjEzNzc4Mzh8MTYyODE4MzcxMDAwMA==/500x</capa>
          </livro>
          <livro isbn="9789897221798">
               <titulo>Galveias</titulo>
               <preco>14,16</preco>
               <editora>Quetzal Editores</editora>
               <capa>https://img.bertrand.pt/images/galveias-jose-luis-peixoto/NDV8MTU4MjYyNDJ8MTEzMjIxNTZ8MTQ0NzI2MjgwNTAwMA==/500x</capa>
          </livro>
          <livro isbn="9789897223563">
               <titulo>O Caminho Imperfeito</titulo>
               <preco>14,16</preco>
               <editora>Quetzal Editores</editora>
               <capa>https://img.bertrand.pt/images/o-caminho-imperfeito-jose-luis-peixoto/NDV8MTk2NzUzNjR8MTU1MDI4Mjl8MTUwNDYwNTgzNzAwMA==/500x</capa>
          </livro>
          <livro isbn="9789897224591">
               <titulo>Autobiografia</titulo>
               <preco>14,16</preco>
               <editora>Quetzal Editores</editora>
               <capa>https://img.bertrand.pt/images/autobiografia-jose-luis-peixoto/NDV8MjEzMzIxOTN8MTcyMTgzNDF8MTU2MDI2NzE0NzAwMA==/500x</capa>
          </livro>
     </escritor>
     <escritor nome="Julian Barnes" id="8">
          <livro isbn="9789897228001">
               <titulo>Amor &amp; C.ª</titulo>
               <preco>15,93</preco>
               <editora>Quetzal Editores</editora>
               <capa>https://img.bertrand.pt/images/amor-e-c-julian-barnes/NDV8MjU2Mzc3NDd8MjE4ODc3MTh8MTY3NjA0MTAxMTAwMA==/500x</capa>
          </livro>
          <livro isbn="9789897224690">
               <titulo>A Única História</titulo>
               <preco>13,28</preco>
               <editora>Quetzal Editores</editora>
               <capa>https://img.bertrand.pt/images/a-unica-historia-julian-barnes/NDV8MjEzMzI0NDV8MTcyMTgzODl8MTU1MjM5MTIwMTAwMA==/500x</capa>
          </livro>
          <livro isbn="9789897226724">
               <titulo>Nada a Temer</titulo>
               <preco>13,28</preco>
               <editora>Quetzal Editores</editora>
               <capa>https://img.bertrand.pt/images/nada-a-temer-julian-barnes/NDV8MjM3OTcyODl8MTk4MTA3MjN8MTU4NDQ3MDgzMDAwMA==/500x</capa>
          </livro>
          <livro isbn="9789897226618">
               <titulo>O Homem do Casaco Vermelho</titulo>
               <preco>16,92</preco>
